name: test

on: [push]

jobs:
  luacheck:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Setup Lua
      uses: leafo/gh-actions-lua@v8.0.0
    -
      name: Setup Luarocks
      uses: leafo/gh-actions-luarocks@v4.0.0
    -
      name: Install Tools
      run: luarocks install luacheck
    -
      name: Run luacheck
      run: |
        luacheck .

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        lua-version:
          - "5.1"
          - "5.2"
          - "5.3"
          - "5.4"
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    -
      name: Generate Certificate For Testing
      run: |
        sh cert/certgen.sh
    -
      name: Setup Lua ${{ matrix.lua-version }}
      uses: leafo/gh-actions-lua@v8.0.0
      with:
        luaVersion: ${{ matrix.lua-version }}
    -
      name: Setup Luarocks
      uses: leafo/gh-actions-luarocks@v4.0.0
    -
      name: Install Tools
      run: |
        luarocks install luacov-coveralls
        luarocks install cluacov
        luarocks install assertex
        luarocks install process
        luarocks install signal
        luarocks install testcase
        luarocks install llsocket 0.11.1
        luarocks install libtls 2.7.4
        luarocks install net 0.25.0
    -
      name: Install
      run: |
        luarocks make
    -
      name: Run Test
      run: |
        testcase --coverage ./test/
    -
      name: Coveralls
      continue-on-error: true
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        luacov-coveralls
