name: test

on:
  push:
    paths-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  luacheck:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mah0x211/lua-ci:latest
    steps:
    -
      name: Checkout
      uses: actions/checkout@v2
    -
      name: Install Tools
      run: luarocks install luacheck
    -
      name: Run luacheck
      run: |
        luacheck .

  test:
    needs: luacheck
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/mah0x211/lua-ci:latest
    strategy:
      matrix:
        lua-version:
          - "5.1.:latest"
          - "5.2.:latest"
          - "5.3.:latest"
          - "5.4.:latest"
        #   - "lj-v2.1:latest"
    steps:
    -
      name: Switch Lua Version
      run: |
        lenv -g use ${{ matrix.lua-version }}
        lua -v || true
    -
      name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    -
      name: Install Test Tools
      run: |
        luarocks install luacov
        luarocks install exec
        luarocks install mkstemp
        luarocks install mkdtemp
        luarocks install mkdir
        luarocks install rmdir
        luarocks install testcase
    -
      name: Install
      run: |
        luarocks make
    -
      name: Run Test
      run: |
        testcase --coverage ./test/
    -
      name: Upload lua coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        files: ./luacov.report.out
        token: ${{ secrets.CODECOV_TOKEN }}
        flags: unittests
    # -
    #   name: Generate coverage reports
    #   run: |
    #     sh ./covgen.sh
    # -
    #   name: Upload c coverage to Codecov
    #   uses: codecov/codecov-action@v2
    #   with:
    #     files: ./coverage/lcov.info
    #     flags: unittests
